'******* CLASS DEFINITION *********************************************

class ReferenceTimeScale {
  +id: Uid
  +authority: AuthorityInfo
  +name: LocalizedStringCollection
  +description: LocalizedStringCollection
' +leapSeconds: LeapSecondRecord[0..*]
}

'class LeapSecondRecord {
'  +time: iso8601DateTime
'  +seconds: Integer
'}

'******* NOTES ********************************************************

'ReferenceTimeScale <|-down- LeapSecondRecord
