
[[common-data]]
== Common data attributes

=== General

[[iso-3166]]
=== Usage of ISO 3166 code elements

////
8.1.3	User-assigned code elements
If users need code elements to represent country names not included in this part of ISO 3166, the series of letters AA, QM to QZ, XA to XZ, and ZZ, and the series AAA to AAZ, QMA to QZZ, XAA to XZZ, and ZZA to ZZZ respectively, and the series of numbers 900 to 999 are available.
////

The <<ISO3166-1>> alpha-2 code list is used in this document
to represent entities or data to indicate names of country or
regions.

These alpha-2 codes from <<ISO3166-1>> are used in this document
for the following meanings that differ from their assignment
in <<ISO3166-1>>:

. `AA` represents entities that are
  international in nature (such as the BIPM) or data intended for
  international application (such as the TODO NEED EXAMPLE),
  (assigned as a "`user-assigned code element`" in <<ISO3166-1,8.1.3>>);

. `XZ` represents entities that are located in international waters
  or data intended for application at international waters
  (assigned as a "`user-assigned code element`" in <<ISO3166-1,8.1.3>>);
--
NOTE: The usage of `XZ` echos the identical practice of <<UNLOCODE>>.
--

. `ZZ` represents entities not operating under or endorsed officially
  by UN member states, or data intended for unofficial use
  (assigned as a "`user-assigned code element`" in <<ISO3166-1,8.1.3>>);

. the range `XA` to `XZ` is reserved for user private use, such as
  to represent entities or data not provided by this document and
  not meant to be used publicly
  (assigned as "`user-assigned code elements`" in <<ISO3166-1,8.1.3>>);

. `EU` represents entities that operate under authority of
  the European Union, or data that is intended to apply to
  the European Union
  (as listed an "`exceptionally reserved`" element at <<ISO3166MA>>);

. `UN` represents entities that operate under authority of
  the United Nations or its specialized agencies, or data that is
  intended for United Nations members or its specialized agencies
  (as listed an "`exceptionally reserved`" element at <<ISO3166MA>>).



=== Data models

The following data models are common to the data models specified in
<<reference-time-scale-authority>> and <<reference-time-scale>>.


==== Localization

LocalizationString represents a single string.

LocalizationCollection represents a collection of localized strings.

The script tag uses script codes from <<ISO15924>> and language codes from <<ISO639-1>>.

//What happens if not provided in user's language?

[plantuml]
....
# include::../models/style.uml.inc[]
include::../models/localized-string.wsd[]
....

