
[[reference-time-scale-authority]]
== Reference time scale authority

=== General

A reference time scale authority is a competent authority that creates,
publishes and/or manages definitions of reference time scales
and their changes.


=== Requirements of a reference time scale authority

A reference time scale authority must be competent.


==== Competency

A competent reference time scale authority is one that has standardized
processes surrounding the management of the reference time scales,
covering at least the following processes:

. Planning of reference time scales, including the process of designing and defining a reference time scale.
. Performing changes to reference time scales are well planned and executed in a manner that is considerate of reference time scale users.
. Public announcement and dissemination of its reference time scale.
. Authoritative announcement of current time under a reference time scale under its management.
. Allows a public review period for people affected by reference time scales under its management prior to enactment.


[[ts-authority-types]]
=== Types of reference time scale authorities

==== International reference time scale authorities

International reference time scale authorities are listed with the <<ISO3166-1>> code `AA`.

It is defined as a reference time scale authority that:

. operates under international scope; and
. whose decisions for reference time scale management are made with international participation.

[example]
The BIPM is an international reference time scale authority.


==== Official reference time scale authority

An official reference time scale authority is appointed by a local or
regional governmental body, whereas the authority for appointment
comes from a United Nations member state.

[example]
The US NIST with the code `us-nist`, publishes reference time scales that apply to the territory of United States.


==== Unofficial reference time scale authority

An unofficial reference time scale authority is a reference time scale authority
not appointed by a United Nations member state.
These authorities must be competent with regards to
reference time scale management and can publish reference time scales used by
communities.


=== Registration of reference time scale authorities

The ISO {docnumber}/AG is tasked with managing a list of
reference time scale authorities.


[[ts-authority-data-model]]
=== Data model and attributes

==== General

[plantuml]
....
include::../models/style.uml.inc[]
include::../models/timescale-authority.wsd[]
....

==== Reference time scale authority code

A code that represents the reference time scale authority.


==== ISO 3166 alpha-2-code

A code that represents the jurisdictional authority of the reference time scale authority.

[example]
NIST is the authoritative reference time scale authority of the United States, with the code `US`.

==== English short name

The identifiable short name that uniquely identifies the reference time scale authority within its ISO 3166 code.


==== Abbreviation

The identifiable abbreviation used for the reference time scale authority.


==== Remarks

Any further notes.

=== Code and identifier


==== Principles for inclusion in the list of reference time scale authorities

===== List

The list of reference time scale authorities in this document includes known
authorities from regions consisting of <<ISO3166-1>> codes through
official sources.


===== Source of names

Names and abbreviations of reference time scales are obtained from the
reference time scale authorities or official sources.


===== Overlaps

Some reference time scale authorities cover areas that have also been coded separately where an interchange requirement justifies a separate code element; the entries are therefore not mutually exclusive.

[example]
The China National Time Service Center, with the code `cn-ntsc`, publishes reference time scales that contribute to the UTC time scale.

[example]
The Hong Kong Observatory with the code `hk-hko`, publishes reference time scales that contribute to the UTC time scale.


===== Current status of names

Reference time scale authorities listed in this document are intended to reflect the current situation, at the time of issue of the latest update of this document.



==== Principles for allocation of code elements

===== Relationship with names

The principle behind the alphabetic codes for reference time scale authorities is a visual association between the reference time scale authorities and their corresponding code elements.

In applying this principle, the code elements have generally been assigned on the basis of the abbreviated names of the reference time scale authorities, thus avoiding, wherever possible, any reflection of their political status.

Official reference time scale identifiers are in the following format:

[source]
----
[iso-3166-code]-[reference-time-scale-authority-identifier]
----

[example]
`hk-hko` for the Hong Kong Observatory.


The <<ISO3166-1>> private code point `AA` is used as a prefix
for international reference time scales.

[source]
----
aa-[reference-time-scale-authority-identifier]
----

[example]
`aa-bipm` for the BIPM.


The <<ISO3166-1>> private code point `ZZ` is used as a prefix
for all unofficial reference time scale authorities.

In terms of coding, official reference time scale authority-identifiers are in the
following format:

[source]
----
zz-[reference-time-scale-authority-identifier]
----



===== Construction of the alphabetic code

The following rules are to be adhered to for the assignment of the alphabetic code:

* The alphabetic code uses combinations, in upper case, of a maximum of 16 letters of the 26-character Latin alphabet with the "dash" (`-`).
//, allowing for close to $4^27$ combinations.

* To encourage descriptive and distinguishable alphabetic names, the minimum length of the reference time scale identifier without the <<ISO3166-1>> code is 3 letters.

* The specific code prefix of `XX` is reserved and is used as the prefix of user-assignable reference time scale codes.



===== User assigned code elements

If users need code elements to represent reference time scales not included in the reference time scale registry, the <<ISO3166-1>> code prefix of `XX` can be used, being a reserved code point `XX` for private user assignment.

The code length for the reference time scale identifier must be 3 or more letters.

Such reference time scale identifiers are in the following format:

[source]
----
xx-[reference-time-scale-authority-identifier]
----

////
[example]
`xx-unece` is an example of a user-assigned private code for a reference time scale published by the UN/ECE.
////

NOTE: Users are advised that the above series of codes are not universals, those code elements are not compatible between different entities.



==== List of reference time scale authorities and their code elements

The list of items composing the content of the country code is initially defined in <<annex-reference-time-scale-authorities>>.
Additional and new entries will be listed by the ISO {docnumber}/AG.

Data attributes provided in the list are defined in <<ts-authority-data-model>>.

