[[introduction]]
== Introduction

=== General

This international standard describes the concepts,
data model representations,
and universally applicable coded representations of
reference time scales and their authorities.

It belongs to the same family of standards as
<<ISO8601-1>> and <<ISO8601-2>>, the international standards
for date and time representation.

This international standard provides code lists
that facilitates the representation of a reference time scale.
Such representation is crucial in knowing the basis of a timestamp,
for example, in the fields of legal metrology, meteorology,
astronomy and geoinformatics.


=== Concepts

This document aims to standardize the concept of a reference time scale,
its parameters and associated concepts for the use of the
international community.

In particular, these concepts are defined in this document:

* reference time scale; and
* reference time scale authority.



=== Data models

This document provides a number of data models that defines
reference time scales and related concepts in fine resolution, allowing
compliant implementations to be able to interoperate.


=== Coded representations

This international standard establishes codes that represent
the following attributes, current or in the past, on the basis
of data obtained from official sources:

* names of reference time scales; and
* names of reference time scale authorities.


=== Registration authority of code lists

This document specifies a registration authority that
manages and disseminates the code lists required by
this document.

The registration authority is not meant to replace existing
computer reference time scale databases, but meant to serve authoritative
reference time scale information created by the reference time scale authorities,
and can be used as an upstream information source to synchronize
existing reference time scale databases.

The mechanism of reference time scale registration given in this
international standard empowers reference time scale authorities
to publish digital definitions of their reference time scales themselves,
therefore allowing users to directly obtain authoritative
reference time scale information from the reference time scale authorities.


=== Priority for practice

This document aims to provide interoperable representations
and mechanisms for the use and management of reference time scales.

It does not express any opinion whatsoever
concerning the legal status of any country, dependency, or other
area named herein, or concerning its frontiers or boundaries.

