@startuml

'******* CONFIGURATION ************************************************
!include style.uml.inc

class iso8601DateTime <<dataType>> {

}

class timeScaleCode <<dataType>> {

}

class MD_SpatialRepresentation <<dataType>> {

}

@enduml
